name: Docker Hub Cleanup

on:
  schedule:
    - cron: "0 0 * * 0"   # Every Sunday

  workflow_dispatch:

jobs:
  cleanup:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Requests
        run: pip install requests

      - name: Run Cleanup
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: python cleanup/cleanup.py

      - name: Upload Log
        uses: actions/upload-artifact@v4
        with:
          name: cleanup-log
          path: cleanup.log
